version: "3"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4597:4567-4597"
      - "8080:8080"
    environment:
      SERVICES: "lambda, iam, stepfunctions, s3"
      DEBUG: "true"
      DATA_DI: ${DATA_DIR- }
      LAMBDA_EXECUTOR: "docker"
      DOCKER_HOST: "unix:///var/run/docker.sock"
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
